version: '3.9'

services:
  nginx:
    build: .
    container_name: academy
    ports: 
      - "80:80"
    volumes:
      - ./html:/user/share/nginx/html:ro
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf:ro
